### PR TITLE
Protein Protein Process

### PR DESCRIPTION
**Pull request by 4ctrl-alt-del**
This process has been fully coded and added to nextflow, ready for testing. This also contains a new download python script which greatly eases the task of downloading all the data required, which sits at 2 TB now.

### CODE REVIEW

**Comment by spficklin** [comment]
Can you add an argument that would allow someone to specify the files they want to download? That way if they don't want the huge string database they  don't have to get it?

**Comment by 4ctrl-alt-del** [comment]
Finished adding requested features:
* Index string script now overwrites any existing database files.
* Added --list and --tasks arguments to download script.

**Comment by 4ctrl-alt-del** [comment]
I also added a --reset argument for the download script that will reset a given list of tasks if they need to be redone. The keyword ALL will reset all tasks.

**Comment by 4ctrl-alt-del** [comment]
Had to fix little issue with gunzip commands, pull request is now ready from my end.

**Comment by spficklin** [comment]
I merged this into the `dev` branch on my own machine.  It's been so long since this has been sitting here (Sorry @4ctrl-alt-del ) taht it made more sense to merge it into the dev branch instead of master beacuse I had to make some changes for nf-core compatibility.  But despite closing this out, the code has been merged!

**Comment by spficklin** [comment]
This PR got rolled into PR #11 and will get merged into master once CI checks pass.

**Pull request closed without merging**
